general.import = [ "onelight.toml" ]

[env]
term= "xterm-256color"

[window]
dimensions = { columns = 80,  lines = 20}
padding = {x = 4, y = 4}
dynamic_padding = true
dynamic_title = true
decorations = "None"

[scrolling]
multiplier = 3

[font]
normal = { family = "Maple Mono NF", style = "Regular" }
bold = { family = "Maple Mono NF", style = "Bold" }
italic = { family = "Maple Mono NF", style = "Italic" }
bold_italic = { family = "Maple Mono NF", style = "Bold Italic" }
size = 11.25
builtin_box_drawing = true

[mouse]
hide_when_typing = true

[[hints.enabled]]
command = "xdg-open" 
hyperlinks = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`\\\\]+"
post_processing = true
mouse = { enabled = true } 
binding = { key = "U", mods = "Control|Shift" }
