general.import = [ "onedark.toml" ]

[window]
dimensions.columns = 80
dimensions.lines = 20
padding.x = 4
padding.y = 4

[font]
normal.family = "Maple Mono NF"
italic.family = "Maple Mono NF"
bold_italic.family = "Maple Mono NF"
size = 11.25
