theme = "kaolin-light"

[editor]
line-number = "relative"
cursor-shape.insert = "bar"
cursor-shape.select = "underline"
cursorline = true
true-color = true
mouse = true

[keys.normal]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
